name: label-issues-when-referenced-by-pr
on:
  pull_request:
    types: [opened, edited, synchronize]
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: read

jobs:
  label-from-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Extract referenced issues & label them
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            // matches #123 or owner/repo#123
            const refs = new Set();
            const local = body.matchAll(/(^|\s)#(\d+)\b/g);
            for (const m of local) refs.add(`${owner}/${repo}#${m[2]}`);
            const cross = body.matchAll(/\b([\w.-]+)\/([\w.-]+)#(\d+)\b/g);
            for (const m of cross) refs.add(`${m[1]}/${m[2]}#${m[3]}`);

            for (const ref of refs) {
              const [o,r,num] = ref.replace('#','/').split('/');
              await github.rest.issues.addLabels({
                owner: o, repo: r, issue_number: Number(num),
                labels: ['pr-crossref']
              });
            }
  label-from-pr-comment:
    if: github.event_name == 'issue_comment' && !!github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Extract referenced issues from PR comment & label them
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.comment.body || "";
            const owner = context.repo.owner;
            const repo  = context.repo.repo;

            const refs = new Set();
            const local = body.matchAll(/(^|\s)#(\d+)\b/g);
            for (const m of local) refs.add(`${owner}/${repo}#${m[2]}`);
            const cross = body.matchAll(/\b([\w.-]+)\/([\w.-]+)#(\d+)\b/g);
            for (const m of cross) refs.add(`${m[1]}/${m[2]}#${m[3]}`);

            for (const ref of refs) {
              const [o,r,num] = ref.replace('#','/').split('/');
              await github.rest.issues.addLabels({
                owner: o, repo: r, issue_number: Number(num),
                labels: ['pr-crossref']
              });
            }
